### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by jerrchen** [OfficeDev/O365-iOS-Snippets#1]
Hi

Possible to update the build instructions?  The pods are out of date, and even with later pods, still issue of code not compiling due unable to find #import <office365_odata_base/MSODataURL.h>

Is this the older O365 API rather than the new unified version?

**Comment by bmitchell287** [comment]
Hi Jerry, thanks for trying out the sample. We haven’t been able to repro this issue yet on our side. The podfile is up to date for this project (version 0.9.0), and we didn’t see that particular error.  The sample worked. For starters would you please try to clone the project locally again, or grab the latest zip, and attempt one more time?

Appreciated.

**Comment by bmitchell287** [comment]
Jerry, I did see that the pod version statement in the sample readme was still pointing to 0.8.3. It has been updated to 0.9.0. This shouldn't affect the sample running.

**Comment by jerrchen** [comment]
I don't think it works, for example the ADALIOS version is 1.2.2 and in your pod file it is 1.2.0 ...  Also the name is ADALiOS in the 'pod list'.

Miadmins-MacBook-Pro-2:Snipplets jerryc$ ls -l
total 8
drwxr-xr-x@ 4 jerryc  staff  782 May  5 15:31 O365-iOS-Snippets
drwxr-xr-x@ 3 jerryc  staff  136 May  5 15:31 O365-iOS-Snippets.xcodeproj
drwxr-xr-x@ 2 jerryc  staff  102 May  5 15:31 O365-iOS-Snippets.xcworkspace
-rwxr-xr-x@ 1 jerryc  staff  239 May  5 15:31 Podfile
Miadmins-MacBook-Pro-2:Snipplets jerryc$ pod install
Analyzing dependencies
[!] Unable to find a specification for `ADALIOS (~> 1.2.0)`
Miadmins-MacBook-Pro-2:Snipplets jerryc$ pod list |grep ADAL
  ADALiOS 1.2.2
Miadmins-MacBook-Pro-2:Snipplets jerryc$ more Podfile
source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '8.0'

target 'O365-iOS-Snippets' do

pod 'ADALIOS', '~> 1.2.0'
pod 'Office365/Outlook', '= 0.9.0'
pod 'Office365/Discovery', '= 0.9.0'
pod 'Office365/Files', '= 0.9.0'

end


Miadmins-MacBook-Pro-2:Snipplets jerryc$ 
===

So I changed the podfile and it pulls.  And then during compile, I am still getting 
#import <office365_odata_base/MSODataURL.h>
not found

**Comment by jerrchen** [comment]
My mac was magically formatted by my IT to be case sensitive.  So that may be the cause of the include problems.  You are including file MSODataURL.h in some files and the real name is "MSODataUrl.h"

**Comment by unpluggedk** [comment]
Hi Jerry,
We will update the the Podfile to 'ADALiOS' as you suggested.  
This does appear to be the case-sensitive issue with file system you brought up. Being in preview, we are still trying to drive for name consistency and will definitely keep track of this.

**Comment by bmitchell287** [comment]
I'm going to close this issue. We've made the podfile update as pointed out. Jerry you can also open an issue against the Office-365-SDK-for-iOS (name consistency) if the problem still exists.
